title: Vehicle Classifier
description: A vehicle classification system using Flask and TensorFlow.
baseurl: "" # Leave this empty for GitHub Pages
url: "https://github.com/Lokesh-meruva/Vehicle-Image-Classification" # Replace <your-username> with your GitHub username
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag